import classNames from "classnames"
import { checkProp } from "../utils"

export const classes = ({ gap, span, offset }) => {

  const cls = classNames(
    "col",
    { "col--gap-0": checkProp(gap, 'm') === "0" },
    { "col--gap-1": checkProp(gap, 'm') === "1" },
    { "col--gap-2": checkProp(gap, 'm') === "2" },
    { "col--gap-3": checkProp(gap, 'm') === "3" },
    { "col--gap-4": checkProp(gap, 'm') === "4" },
    { "col--gap-5": checkProp(gap, 'm') === "5" },
    { "col--gap-6": checkProp(gap, 'm') === "6" },
    { "col--gap-7": checkProp(gap, 'm') === "7" },
    { "col--gap-8": checkProp(gap, 'm') === "8" },
    { "col--gap-9": checkProp(gap, 'm') === "9" },
    { "col--gap-10": checkProp(gap, 'm') === "10" },
    { "mqt-col--gap-0": checkProp(gap, 't') === "0" },
    { "mqt-col--gap-1": checkProp(gap, 't') === "1" },
    { "mqt-col--gap-2": checkProp(gap, 't') === "2" },
    { "mqt-col--gap-3": checkProp(gap, 't') === "3" },
    { "mqt-col--gap-4": checkProp(gap, 't') === "4" },
    { "mqt-col--gap-5": checkProp(gap, 't') === "5" },
    { "mqt-col--gap-6": checkProp(gap, 't') === "6" },
    { "mqt-col--gap-7": checkProp(gap, 't') === "7" },
    { "mqt-col--gap-8": checkProp(gap, 't') === "8" },
    { "mqt-col--gap-9": checkProp(gap, 't') === "9" },
    { "mqt-col--gap-10": checkProp(gap, 't') === "10" },
    { "mqd-col--gap-0": checkProp(gap, 'd') === "0" },
    { "mqd-col--gap-1": checkProp(gap, 'd') === "1" },
    { "mqd-col--gap-2": checkProp(gap, 'd') === "2" },
    { "mqd-col--gap-3": checkProp(gap, 'd') === "3" },
    { "mqd-col--gap-4": checkProp(gap, 'd') === "4" },
    { "mqd-col--gap-5": checkProp(gap, 'd') === "5" },
    { "mqd-col--gap-6": checkProp(gap, 'd') === "6" },
    { "mqd-col--gap-7": checkProp(gap, 'd') === "7" },
    { "mqd-col--gap-8": checkProp(gap, 'd') === "8" },
    { "mqd-col--gap-9": checkProp(gap, 'd') === "9" },
    { "mqd-col--gap-10": checkProp(gap, 'd') === "10" },

    { "col--span-0": checkProp(span, 'm') === "0" },
    { "col--span-1": checkProp(span, 'm') === "1" },
    { "col--span-2": checkProp(span, 'm') === "2" },
    { "col--span-3": checkProp(span, 'm') === "3" },
    { "col--span-4": checkProp(span, 'm') === "4" },
    { "col--span-5": checkProp(span, 'm') === "5" },
    { "col--span-6": checkProp(span, 'm') === "6" },
    { "col--span-7": checkProp(span, 'm') === "7" },
    { "col--span-8": checkProp(span, 'm') === "8" },
    { "col--span-9": checkProp(span, 'm') === "9" },
    { "col--span-10": checkProp(span, 'm') === "10" },
    { "col--span-11": checkProp(span, 'm') === "11" },
    { "col--span-12": checkProp(span, 'm') === "12" },
    { "mqt-col--span-0": checkProp(span, 't') === "0" },
    { "mqt-col--span-1": checkProp(span, 't') === "1" },
    { "mqt-col--span-2": checkProp(span, 't') === "2" },
    { "mqt-col--span-3": checkProp(span, 't') === "3" },
    { "mqt-col--span-4": checkProp(span, 't') === "4" },
    { "mqt-col--span-5": checkProp(span, 't') === "5" },
    { "mqt-col--span-6": checkProp(span, 't') === "6" },
    { "mqt-col--span-7": checkProp(span, 't') === "7" },
    { "mqt-col--span-8": checkProp(span, 't') === "8" },
    { "mqt-col--span-9": checkProp(span, 't') === "9" },
    { "mqt-col--span-10": checkProp(span, 't') === "10" },
    { "mqt-col--span-11": checkProp(span, 't') === "11" },
    { "mqt-col--span-12": checkProp(span, 't') === "12" },
    { "mqd-col--span-0": checkProp(span, 'd') === "0" },
    { "mqd-col--span-1": checkProp(span, 'd') === "1" },
    { "mqd-col--span-2": checkProp(span, 'd') === "2" },
    { "mqd-col--span-3": checkProp(span, 'd') === "3" },
    { "mqd-col--span-4": checkProp(span, 'd') === "4" },
    { "mqd-col--span-5": checkProp(span, 'd') === "5" },
    { "mqd-col--span-6": checkProp(span, 'd') === "6" },
    { "mqd-col--span-7": checkProp(span, 'd') === "7" },
    { "mqd-col--span-8": checkProp(span, 'd') === "8" },
    { "mqd-col--span-9": checkProp(span, 'd') === "9" },
    { "mqd-col--span-10": checkProp(span, 'd') === "10" },
    { "mqd-col--span-11": checkProp(span, 'd') === "11" },
    { "mqd-col--span-12": checkProp(span, 'd') === "12" },

    { "col--offset-0": checkProp(offset, 'm') === "0" },
    { "col--offset-1": checkProp(offset, 'm') === "1" },
    { "col--offset-2": checkProp(offset, 'm') === "2" },
    { "col--offset-3": checkProp(offset, 'm') === "3" },
    { "col--offset-4": checkProp(offset, 'm') === "4" },
    { "col--offset-5": checkProp(offset, 'm') === "5" },
    { "col--offset-6": checkProp(offset, 'm') === "6" },
    { "col--offset-7": checkProp(offset, 'm') === "7" },
    { "col--offset-8": checkProp(offset, 'm') === "8" },
    { "col--offset-9": checkProp(offset, 'm') === "9" },
    { "col--offset-10": checkProp(offset, 'm') === "10" },
    { "col--offset-11": checkProp(offset, 'm') === "11" },
    { "col--offset-12": checkProp(offset, 'm') === "12" },
    { "mqt-col--offset-0": checkProp(offset, 't') === "0" },
    { "mqt-col--offset-1": checkProp(offset, 't') === "1" },
    { "mqt-col--offset-2": checkProp(offset, 't') === "2" },
    { "mqt-col--offset-3": checkProp(offset, 't') === "3" },
    { "mqt-col--offset-4": checkProp(offset, 't') === "4" },
    { "mqt-col--offset-5": checkProp(offset, 't') === "5" },
    { "mqt-col--offset-6": checkProp(offset, 't') === "6" },
    { "mqt-col--offset-7": checkProp(offset, 't') === "7" },
    { "mqt-col--offset-8": checkProp(offset, 't') === "8" },
    { "mqt-col--offset-9": checkProp(offset, 't') === "9" },
    { "mqt-col--offset-10": checkProp(offset, 't') === "10" },
    { "mqt-col--offset-11": checkProp(offset, 't') === "11" },
    { "mqt-col--offset-12": checkProp(offset, 't') === "12" },
    { "mqd-col--offset-0": checkProp(offset, 'd') === "0" },
    { "mqd-col--offset-1": checkProp(offset, 'd') === "1" },
    { "mqd-col--offset-2": checkProp(offset, 'd') === "2" },
    { "mqd-col--offset-3": checkProp(offset, 'd') === "3" },
    { "mqd-col--offset-4": checkProp(offset, 'd') === "4" },
    { "mqd-col--offset-5": checkProp(offset, 'd') === "5" },
    { "mqd-col--offset-6": checkProp(offset, 'd') === "6" },
    { "mqd-col--offset-7": checkProp(offset, 'd') === "7" },
    { "mqd-col--offset-8": checkProp(offset, 'd') === "8" },
    { "mqd-col--offset-9": checkProp(offset, 'd') === "9" },
    { "mqd-col--offset-10": checkProp(offset, 'd') === "10" },
    { "mqd-col--offset-11": checkProp(offset, 'd') === "11" },
    { "mqd-col--offset-12": checkProp(offset, 'd') === "12" },
  )

  return cls
}